//#include "szyfr_cezara.cpp"
//#include "basic_sort.cpp"
//#include "szyfr_afiniczny.cpp"
//#include "misc.cpp"
//#include "szyfr_vigenere.cpp"
//#include "srednia.cpp"
//#include "suma_cyfr.cpp"
//#include "rozwiaz_uklad.cpp"
////#include "obliczanie_wielomianu.cpp"
//#include "pierwiastek.cpp"
////#include "silnia_reku.cpp"
//#include "slabnia_reku.cpp"
//#include "obliczanie_wielomianu_reku.cpp"
//#include "funkcja_ackermanna.cpp"
//#include "fun.cpp"
//#include "ciekawe_mnozenia.cpp"
//#include "euklides_reku.cpp"
//#include "symbol_newtona.cpp"
//#include "binarny.cpp"
//#include "korale.cpp"
//#include "bit_test.cpp"
//#include "calki.cpp"
//#include "fraktale.cpp"
//#include "obliczanie_pi.cpp"
//#include "znajdowanie_miejsca_zerowego.cpp"
//#include "io_files.cpp"
//#include "odwracanie_liczb.cpp"
//#include "moc_liczby.cpp"
//#include "trojkaty.cpp"
//#include "ulamki.cpp"
//#include "struktury.cpp"
#include "vectors.cpp"
#include "baza_danych.cpp"

int main() {
    runVector();
}